"""rename service duration to minimum duration

Revision ID: 180815037cf5
Revises: 35edde4a66fe
Create Date: 2026-09-08 10:24:05.625794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180815037cf5'
down_revision: Union[str, Sequence[str], None] = '35edde4a66fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'services',
        'duration_minutes',
        new_column_name='minimum_duration_minutes'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'services',
        'minimum_duration_minutes',
        new_column_name='duration_minutes'
    )
    # ### end Alembic commands ###
