"""add duration minutes to services

Revision ID: 35edde4a66fe
Revises: bd08c4a613eb
Create Date: 2026-09-07 16:48:07.041968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35edde4a66fe'
down_revision: Union[str, Sequence[str], None] = 'bd08c4a613eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'services',
        sa.Column(
            'duration_minutes',
            sa.Integer(),
            nullable=False,
            server_default='180'
        )
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###
